### ISSUE TITLE
Feature request: recurse after update

### ISSUE THREAD

**Issue by adjohnson916** [awnist/js-traverse-async#3]

**Comment by qoby** [comment]
Is this a request? More info?

**Comment by adjohnson916** [comment]
@qoby Yes, this is a feature request. Updated title for clarity. [Here's a repo](https://github.com/adjohnson916/traverse-recurse) I've created with examples demonstrating how traverse-async doesn't recurse on new values in updates, compared to the synchronous traverse module from substack.

**Comment by qoby** [comment]
Fixed by #2

**Comment by adjohnson916** [comment]
@qoby Thanks.

If you're curious, I started working on async support for substack's traverse module [here](https://github.com/adjohnson916/js-traverse/tree/async) and I've submitted [this PR](https://github.com/substack/js-traverse/pull/47).

**Comment by qoby** [comment]
I don't consider it a breaking change since it's opt-in per node and not default behavior. Thanks for push reminder. If you ever dip into promises in a complex object, check out when-traverse. I'm using a fork of that on some internal projects.

**Comment by AndersDJohnson** [comment]
@qoby Ah yes, I see now how you've implemented it as opt-in.

Yes, thanks, I've looked at `when-traverse` and it seems like a good option too. My PR to `traverse` would be a lighter callback-based implementation though - `when-traverse` wants to include `bluebird` promises as a dependency as well.
